### PR TITLE
Jaybell/update ng v13

### LINKED ISSUE #92: Ivy Distribution Error
When I upgraded to Angular 13, I am getting this message:

```typescript
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-skeleton-loader [es2015/esm2015] (git+https://github.com/willmendesneto/ngx-skeleton-loader.git)
Encourage the library authors to publish an Ivy distribution.
```

J

### PR DESCRIPTION
**Pull request by yharaskrik**
**Please check if the PR fulfills these requirements**

- [ ] The commit messages follow these
      [guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** _(check one with "x")_

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other. Please describe:

If it is a Bugfix, please describe the root cause and what could have been done to prevent it…

**What is the current behavior?** _(You can link to an open issue here, add screenshots…)_
Compiled with VE

**What is the new behavior?**
Compiled for Ivy

**Does this PR introduce a breaking change?** _(check one with "x")_

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: …

Will need to be using Angular 12+

**Other information (if applicable)**:

Resolves #92

---

_Please @mention @people to review this PR…_

### CODE REVIEW

**Comment by logerk46** [comment]
Hi guys,

any updates when this PR will be accepted?

Thanks

**Comment by soori-reddy** [comment]
any ETA ?

**Comment by willmendesneto** [comment]
Hey folks! First and foremost, massive kudos for jumping in!

Apologies for the delay, I'm getting up and running after covid and I'm looking at that in these days. Giving you some updates just to make sure I'm on it!

**Comment by willmendesneto** [comment]
Hey @yharaskrik  Thanks for raising this pull request.

About the code changes, LGTM! Just 1 thing that's missing, which is to align the `.nvmrc` file to the same NodeJS version as in Circle CI config specs `v14.18.2`.

The issue with the pipeline itself is because Code Coverage is not adding `.lcov` files as output after the changes. This is something that can be fixed later since this is adding way more value than that at the moment. In that case, could you comment the command on `.curcleci/config.yml`, please? I'm about to add the changes as suggestion here.

Please, ping me as soon as we have these points in place. So that I can merge this (fantastic) pull request and publish a new version.

**Comment by yharaskrik** [comment]
@willmendesneto done

**Pull request merged**
