### PR TITLE
refactor: use ngDevMode to drop code in production build

### PR DESCRIPTION
**Pull request by rafaelss95**
**Please check if the PR fulfills these requirements**

- [x] The commit messages follow these
      [guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** _(check one with "x")_

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other. Please describe:

If it is a Bugfix, please describe the root cause and what could have been done to prevent it…

**What is the current behavior?** _(You can link to an open issue here, add screenshots…)_
The code block inside `isDevMode()` is not being dropped in production build.

**What is the new behavior?**
Use `ngDevMode` instead.

Check this article https://netbasal.com/environment-based-dead-code-elimination-in-angular-54eec1f92a65 or https://github.com/angular/angular/blob/c9fe455fa2c34ba0de6edbecfeca8c86ccbebe3a/packages/forms/src/directives/shared.ts#L41, for example.

**Does this PR introduce a breaking change?** _(check one with "x")_

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: …

**Other information (if applicable)**:

---

_Please @mention @people to review this PR…_
@willmendesneto

### CODE REVIEW

**Comment by willmendesneto** [comment]
@rafaelss95 Thanks for raising this pull request. However, this is something that we shouldn't use.

Firstly, it's accessing the framework internals, which is not recommended. Secondly, this is pretty much the same as it is implemented via `isDevMode`, which is safest way and recommended by the Angular Docs. More details about the implementation in https://github.com/angular/angular/blob/70b4816cd5fd51cfabd699c4c1cda51feaa1fa72/packages/core/src/util/is_dev_mode.ts#L30-L33

Based on that, I'm closing this ticket. Thanks again for raising this pull request!

**Comment by rafaelss95** [comment]
Hey @willmendesneto thanks for the response...

> Firstly, it's accessing the framework internals, which is not recommended.

In that case, the article from Netanel I put in the PR description (https://netbasal.com/environment-based-dead-code-elimination-in-angular-54eec1f92a65), for example, is recommending a non-recommended approach? Could you send us an original resource saying that this isn't recommended? By the way, `@angular/components` team, for example, which is in another repo from `@angular` uses it quite a lot as you can [**see here**](https://github.com/angular/components/search?q=ngdevmode).

> Secondly, this is pretty much the same as it is implemented via `isDevMode`, which is safest way and recommended by the Angular Docs. More details about the implementation in https://github.com/angular/angular/blob/70b4816cd5fd51cfabd699c4c1cda51feaa1fa72/packages/core/src/util/is_dev_mode.ts#L30-L33

Well, yeah, we do agree that the implementation is almost the same, however the intention of `ngDevMode` is to perform an action that isn't possible with `isDevMode()`: strip unused code from production build. Actually this console is being bundled in production without being used. Btw, you can try this in [Terser REPL](https://try.terser.org/).

**Comment by willmendesneto** [comment]
Hi @rafaelss95 . Let me try to answer that:

> In that case, the article from Netanel I put in the PR description (https://netbasal.com/environment-based-dead-code-elimination-in-angular-54eec1f92a65), for example, is recommending a non-recommended approach?

Actually, it is. Since it's not documented and the only place used is on some internal Angular monorepo packages, the recommended method is the one on Angular Docs - https://angular.io/api/core/isDevMode - and I wouldn't recommend following this approach since it might have breaking changes.

> Could you send us an original resource saying that this isn't recommended?

Who's "us"?

> Well, yeah, we do agree that the implementation is almost the same, however with the ngDevMode is possible to perform an action that isn't possible with isDevMode(): strip unused code from production build. Actually this console is being bundled in production without being used. Btw, you can try this in Terser REPL.

I would also recommend the usage from NX or, in this case, Angular CLI build. Also, I would recommend you to have a read in this document as well https://github.com/willmendesneto/ngx-skeleton-loader/blob/master/CODE_OF_CONDUCT.md

**Comment by rafaelss95** [comment]
> Actually, it is. Since it's not documented and the only place used is on some internal Angular monorepo packages, the recommended method is the one on Angular Docs - https://angular.io/api/core/isDevMode - and I wouldn't recommend following this approach since it might have breaking changes.

Ok, I see your point.

> Who's "us"?

Me and the team I'm currently working on. We're creating a monorepo and this lib is one of we're using to standarize the animations part.

> I would also recommend the usage from NX or, in this case, Angular CLI build.

Yes, the Angular CLI build uses the Terser under the hood to set global variables like `ngDevMode` and that's why I sent the link of it.

> Also, I would recommend you to have a read in this document as well https://github.com/willmendesneto/ngx-skeleton-loader/blob/master/CODE_OF_CONDUCT.md

Thanks for that and thanks again for the great lib :)

**Comment by willmendesneto** [comment]
Regards to Terser, what I was trying to explain is that this will be aligned potentially by Angular CLI team and this is something that should be avoided to be used directly. So unless the project needs some extreme performance boost, this change won’t be necessary in a short time.

**Pull request closed without merging**
