### PR TITLE
build: update to angular v15

### PR DESCRIPTION
**Pull request by chimurai**
**Please check if the PR fulfills these requirements**

- [x] The commit messages follow these
      [guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** _(check one with "x")_

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Other. Please describe:

If it is a Bugfix, please describe the root cause and what could have been done to prevent it…

**What is the current behavior?** _(You can link to an open issue here, add screenshots…)_

**What is the new behavior?**

**Does this PR introduce a breaking change?** _(check one with "x")_

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: …

Will need to be using Angular 15+

**Other information (if applicable)**:

---

_Please @mention @people to review this PR…_

### CODE REVIEW

**Comment by chimurai** [comment]
- updated `ng13` to `ng14`
- updated `ng14` to `ng15`
- updated circleci to use `cimg/node` with `node v14.20.0`
- fixed sudo usage in `.circleci/config.yml`

**Comment by chimurai** [comment]
👋 friendly ping to review the PR @willmendesneto

**Comment by willmendesneto** [comment]
That's amazing, @chimurai ! 

I'll check that in details tomorrow and I'll reply in here. Thanks for that, mate! <3

**Review by willmendesneto — APPROVED** [review]
Nicely done @chimurai ! Thanks for the contribution 🎉

**Pull request merged**
