### PR TITLE
build: update to angular 16

### PR DESCRIPTION
**Pull request by chimurai**
**Please check if the PR fulfills these requirements**

- [x] The commit messages follow these
      [guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** _(check one with "x")_

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Other. Please describe:

If it is a Bugfix, please describe the root cause and what could have been done to prevent it…

**What is the current behavior?** _(You can link to an open issue here, add screenshots…)_

**What is the new behavior?**

**Does this PR introduce a breaking change?** _(check one with "x")_

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: …

Will need to be using Angular 16+

**Other information (if applicable)**:

---

_Please @mention @people to review this PR…_

cc: @willmendesneto

### CODE REVIEW

**Comment by willmendesneto** [comment]
Hi @chimurai ! Thanks for the pull request! 

Let me just check the changes and run on my local. I can see the ESLint comment are not necessary anymore, so just need to check if I need to update something in a subsequent pull request or something and I'll get back to you shortly!

**Comment by jacewardell** [comment]
@willmendesneto is there any progress on reviewing this PR? I'm hoping to upgrade to Angular 16 soon and this is blocking that.

**Review by willmendesneto — APPROVED** [review]
LGTM! Thanks @chimurai !

**Comment by willmendesneto** [comment]
Happy to share these changes are now available on the latest version of `ngx-skeleton-loader`

Please, update your project dependencies to use the version `ngx-skeleton-loader@8.0.0` 🚀 🚀 🚀

**Pull request merged**
